### ISSUE TITLE
npm package?

### ISSUE THREAD

**Issue by myst729** [wentin/underlineJS#34]
It would be nice if I could install this lib via npm.

**Comment by mspae** [comment]
You could try https://www.npmjs.com/package/typographic-underline-canvas – I created it in the wake of https://github.com/wentin/underlineJS/issues/33 – It's a bit unstable, but if you have any ideas/some time to improve it feel free to open a PR.

**Comment by myst729** [comment]
@mspae Great, I'll give it a try.
